<div class="column">
<?php if ($this->group_tree->hasChildren()) { ?>
<?= Adminko\View::block('module/work/menu', array('group_tree' => $this->group_tree, 'depth' => 0)) ?>
<?php } ?>
</div>
<?php if ($this->group_tree->hasChildren() && $this->work_list) { ?>
<div class="separator"></div>
<?php } ?>
<?php if ($this->work_list) { ?>
<div class="column">
<?php $work_list_index = 0; ?>
<?php foreach ($this->work_list as $work_item) { ?>
    <?= ++$work_list_index ?>.&nbsp;&nbsp;<a href="<?= $work_item->getWorkUrl() ?>"><?= $this->escape($work_item->getWorkTitle()) ?></a><br/>
<?php } ?>
</div>
<?php } ?>
