<div class="work">
<?php if ($prev_work = $this->work_item->getPrevWork()) { ?>
<noindex><a class="prev" href="<?= $prev_work->getWorkUrl() ?>" title="<?= trim($this->escape($prev_work->getWorkTitle())) ?>">&larr;</a></noindex>
<?php } ?>
<?php if ($next_work = $this->work_item->getNextWork()) { ?>
<noindex><a class="next" href="<?= $next_work->getWorkUrl() ?>" title="<?= trim($this->escape($next_work->getWorkTitle())) ?>">&rarr;</a></noindex>
<?php } ?>
<? $workTitle = preg_match('/^".+\.\.\."$/', $this->work_item->getWorkTitle()) ? '* * *' : $this->work_item->getWorkTitle(); ?>
<h3><?= trim($workTitle) ?></h3>
<p><?= nl2br(rtrim($this->work_item->getViewText())) ?><?php if ($this->work_item->getWorkComment()) { ?><br/>
<br/>
<?= trim($this->work_item->getWorkComment()) ?><?php } ?></p>
</div>
