<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= $this->escape($this->meta_title) ?></title>
        <meta name="keywords" content="<?= $this->escape($this->meta_keywords) ?>"/> 
        <meta name="description" content="<?= $this->escape($this->meta_description) ?>"/> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="shortcut icon" href="/image/favicon.ico"/>
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
    </head>
    <body>
        <div class="header">
            <div class="wrapper">
                <div class="left">
<?= $this->path ?>
                </div>
                <div class="right">
                    <a href="/">Поэт Хренов</a>
                </div>
            </div>
        </div>
        <div class="content">
<?= $this->content ?>
        </div>
        <div class="footer">
            <div class="wrapper">
                <div class="left">
<?= $this->menu ?>
                </div>
                <div class="right">
<?= $this->sidebar ?>
                </div>
            </div>
        </div>
    </body>
</html>
