services:
    stimulus.helper:
        class: Symfony\UX\StimulusBundle\Helper\StimulusHelper
        # Breaking circular dependency: stimulus.helper -> twig -> extension -> stimulus.helper
        arguments:
            - null

    Symfony\UX\StimulusBundle\Twig\StimulusTwigExtension:
        arguments:
            - '@stimulus.helper'
        tags:
            - { name: twig.extension, priority: -10 }
