<link rel="stylesheet" href="/css/lightbox.css" />

<script src="/js/jquery.min.js"></script>
<script src="/js/lightbox.min.js"></script>

<div class="gallery">
<?php foreach ($this->picture_list as $picture_item) { ?>
    <a href="<?= $picture_item->getPictureImage() ?>" data-lightbox="gallery" data-title="<?= $picture_item->getPictureTitle() ?> (<?= Adminko\Date::get($picture_item->getPictureDate()) ?>)">
        <img src="<?= $picture_item->getPictureImage() . '/r/150/150' ?>" title="<?= $picture_item->getPictureTitle() ?> (<?= Adminko\Date::get($picture_item->getPictureDate()) ?>)">
    </a>
<?php } ?>
</div>

<?= $this->pages ?>

<script>
    lightbox.option({
        'albumLabel': ''
    })
</script>
