# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

security:
    resource: '../src/Controller/SecurityController.php'
    type: attribute

site:
    resource: '../src/Controller/SiteController.php'
    type: attribute
    condition: "request.server.get('APP_SITE_CONTEXT') == 'www'"

blog:
    resource: '../src/Controller/BlogController.php'
    type: attribute
    condition: "request.server.get('APP_SITE_CONTEXT') == 'blog'"

work:
    resource: '../src/Controller/WorkController.php'
    type: attribute
    condition: "request.server.get('APP_SITE_CONTEXT') == 'work'"

audio:
    resource: '../src/Controller/AudioController.php'
    type: attribute
    condition: "request.server.get('APP_SITE_CONTEXT') == 'work'"
