# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Admin\UserAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, manager_type: orm, group: admin, label: User }
        calls:
            - [setPasswordHasher, ['@security.user_password_hasher']]

    App\Admin\TagAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\Tag, manager_type: orm, group: blog, label: Tags }

    App\Admin\BlogPostAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\BlogPost, manager_type: orm, group: blog, label: Posts }

    App\Admin\BlogCommentAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\BlogComment, manager_type: orm, group: blog, label: Comments }

    App\Admin\PoemAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\Poem, manager_type: orm, group: poems, label: Poems }

    App\Admin\PoemVersionAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\PoemVersion, manager_type: orm, group: poems, label: Versions }

    App\Admin\WorkGroupAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\WorkGroup, manager_type: orm, group: work, label: Groups }

    App\Admin\WorkAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\Work, manager_type: orm, group: work, label: Works }

    App\Admin\WorkCommentAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\WorkComment, manager_type: orm, group: work, label: Comments }

    App\Admin\WorkVoteAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\WorkVote, manager_type: orm, group: work, label: Votes }

    App\Admin\AudioAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\Audio, manager_type: orm, group: media, label: Audio }

    App\Admin\PictureAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\Picture, manager_type: orm, group: media, label: Pictures }

    App\Admin\StaticTextAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Entity\StaticText, manager_type: orm, group: site, label: Static Texts }
