<?php if( $this -> count > $this -> by_page ) { ?>
<div class="pages">
<?php 		if( $this -> prev_page ) { ?>
    <a href="<?= $this->escape( $this -> prev_page['link'] ) ?>">&larr;</a>
<?php 		} else { ?>
    <b>&larr;</b>
<?php 		} ?>
<?php 		foreach( $this -> pages as $page ) { ?>
<?php 			if( $page['link'] ) { ?>
    <a href="<?= $this->escape( $page['link'] ) ?>"><? if ( $page['number'] ) { ?><?= $page['number'] ?><? } else { ?>&hellip;<? } ?></a>
<?php 			} else { ?>
    <b><?= $page['number'] ?></b>
<?php 			} ?>
<?php		} ?>
<?php 		if( $this -> next_page ) { ?>
    <a href="<?= $this->escape( $this -> next_page['link'] ) ?>">&rarr;</a>
<?php 		} else { ?>
    <b>&rarr;</b>
<?php 		} ?>
</div>
<?php } ?>
